version: '3.8'

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE__USERNAME}   
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE__PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE__DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgesql/data